// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArBJWke8wejbnYjjnRC-zEPm5mIQSjB_c',
    appId: '1:427429554352:web:6bb9e8ec488df952ec3375',
    messagingSenderId: '427429554352',
    projectId: 'edublocks-research-tool',
    authDomain: 'edublocks-research-tool.firebaseapp.com',
    storageBucket: 'edublocks-research-tool.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpl7RO9YWTnMWF369mbNWd-MAMHk0xbtY',
    appId: '1:427429554352:android:e0c7605c96bde6f9ec3375',
    messagingSenderId: '427429554352',
    projectId: 'edublocks-research-tool',
    storageBucket: 'edublocks-research-tool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrOZGYnpf71x8HgSzXRfvCLo-iGZyALoQ',
    appId: '1:427429554352:ios:5fb8165ef8792927ec3375',
    messagingSenderId: '427429554352',
    projectId: 'edublocks-research-tool',
    storageBucket: 'edublocks-research-tool.firebasestorage.app',
    iosBundleId: 'com.example.edublocksFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrOZGYnpf71x8HgSzXRfvCLo-iGZyALoQ',
    appId: '1:427429554352:ios:5fb8165ef8792927ec3375',
    messagingSenderId: '427429554352',
    projectId: 'edublocks-research-tool',
    storageBucket: 'edublocks-research-tool.firebasestorage.app',
    iosBundleId: 'com.example.edublocksFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArBJWke8wejbnYjjnRC-zEPm5mIQSjB_c',
    appId: '1:427429554352:web:bc4836f87b760747ec3375',
    messagingSenderId: '427429554352',
    projectId: 'edublocks-research-tool',
    authDomain: 'edublocks-research-tool.firebaseapp.com',
    storageBucket: 'edublocks-research-tool.firebasestorage.app',
  );

  static Future<int> initializeFirebase() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    return 0;
  }
}
