name: edublocks_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  provider: ^6.1.5
  collection: ^1.18.0
  just_audio: ^0.9.36
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  auto_size_text: ^3.0.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - app_assets/
    - app_assets/block_images/
    - app_assets/block_images/import/
    - app_assets/block_images/lists/
    - app_assets/block_images/logic/ageLessThan11/
    - app_assets/block_images/logic/countLessThan10/
    - app_assets/block_images/logic/else/
    - app_assets/block_images/logic/elseIfAgeLessThan16/
    - app_assets/block_images/logic/elifClass/
    - app_assets/block_images/loops/for_i_inRange/
    - app_assets/block_images/loops/whileGrades/
    - app_assets/block_images/loops/whileTrue/
    - app_assets/block_images/loops/
    - app_assets/block_images/statements/
    - app_assets/block_images/variables/
    - app_assets/category_icons/
    - app_assets/sounds/
